### PR TITLE
fix icon display on WordPress 4.4

### LINKED ISSUE #13: Markdown Button Missing after Upgrade to WP 4.4
After updating to WordPress 4.4, the "M" button on the <strong>Publish</strong> box is no longer there.  Posts that already existed and were using Markdown continued to use it but there is no longer a way to set new posts to use Markdown.

## Pre-4.4
68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f31313939382f3135333930382f30643865626437302d373630392d313165322d396632372d3235613838646466363938622e6a7067

## 4.4
screenshot 2015-12-18 15 58 44

### PR DESCRIPTION
**Pull request by willnorris**
metaboxes use h2 instead of h3 for titles now (https://wp.me/p2AvED-41H) This change now only works for WordPress 4.4; I'm not sure how concerned we should be about backward compatibility.

Also remove double slash in image URLs (plugin_dir_url already includes trailing slash) and vertically align markdown button in middle instead of bottom.

fixes #13

### CODE REVIEW

**Comment by salcode** [comment]
What are your thoughts on targeting both `h2` and `h3`for capability with pre-4.4?

**Comment by salcode** [comment]
I think this will work https://github.com/salcode/markdown-on-save/tree/compat-4-4-h2-heading-13

**Comment by willnorris** [comment]
yeah, that looks better.  I couldn't get the coffee file to compile properly, and was just editing the js file by hand, so didn't try for anything more complex.  Your patch is definitely the right way to do it though.

**Comment by willnorris** [comment]
I've updated this pull request to now include your patch instead.

**Pull request merged**
